// @generated by defect-llm-codegen — do not edit by hand.
// Source OAS: crates/llm/oas/anthropic.yaml
// Re-run via `cargo run -p defect-llm-codegen -- anthropic`.
#![allow(
    clippy::manual_async_fn,
    clippy::needless_return,
    clippy::single_match,
    clippy::match_single_binding,
    clippy::too_many_arguments,
    clippy::large_enum_variant,
    clippy::enum_variant_names,
    dead_code,
    unused_imports,
)]

/// # Anthropic Messages API
///
/// 本地裁剪版的 Anthropic Messages API OAS。仅保留 defect-llm 实际用到
/// 的端点（v0：/v1/models；后续会加 /v1/messages）。每次 Anthropic
/// 上游加字段时，手动同步对应 schema 段。
///
/// - **Version:** `2023-06-01`
pub mod spec {}
pub mod components {
    #![allow(deprecated)]
    #![allow(unreachable_patterns)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(clippy::all, clippy::pedantic)]
    /// 固定字面量 "model"。
    #[derive(
        Debug,
        Clone,
        Copy,
        PartialEq,
        Eq,
        ::serde::Serialize,
        ::serde::Deserialize
    )]
    pub enum ModelInfoType {
        #[serde(rename = "model")]
        Model,
    }
    impl ::std::fmt::Display for ModelInfoType {
        fn fmt(&self, __f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match self {
                Self::Model => ::std::write!(__f, "model"),
            }
        }
    }
    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct ModelInfo {
        /// 固定字面量 "model"。
        pub r#type: ModelInfoType,
        /// 模型 id，例如 "claude-3-5-sonnet-20241022"。
        pub id: String,
        /// 人类可读名称。
        pub display_name: String,
        /// ISO-8601 时间戳。
        pub created_at: String,
    }
    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct ListModelsResponse {
        pub data: Vec<ModelInfo>,
        /// 后面还有页时为 true。
        pub has_more: bool,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub first_id: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        pub last_id: Option<String>,
    }
    #[derive(
        Debug,
        Clone,
        Copy,
        PartialEq,
        Eq,
        ::serde::Serialize,
        ::serde::Deserialize
    )]
    pub enum ErrorResponseType {
        #[serde(rename = "error")]
        Error,
    }
    impl ::std::fmt::Display for ErrorResponseType {
        fn fmt(&self, __f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match self {
                Self::Error => ::std::write!(__f, "error"),
            }
        }
    }
    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct ErrorResponseError {
        /// Anthropic 错误分类：invalid_request_error /
        /// authentication_error / permission_error /
        /// not_found_error / rate_limit_error /
        /// api_error / overloaded_error。
        pub r#type: String,
        pub message: String,
    }
    #[derive(Debug, Clone, PartialEq, ::serde::Serialize, ::serde::Deserialize)]
    pub struct ErrorResponse {
        pub r#type: ErrorResponseType,
        pub error: ErrorResponseError,
    }
}
pub mod operations {
    #![allow(deprecated)]
    #![allow(unreachable_patterns)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(clippy::all, clippy::pedantic)]
    pub mod v1 {
        pub mod models {
            pub mod get {
                #[derive(Debug, Clone, PartialEq)]
                /// # List available models
                /// 返回当前 API key 可见的全部模型清单。分页字段 v0 不用。
                pub struct Request {
                    pub before_id: Option<String>,
                    pub after_id: Option<String>,
                    pub limit: Option<i64>,
                }
                impl Request {
                    /// `GET /v1/models`
                    /// Operation ID: `listModels`.
                    pub const METHOD: ::http::Method = ::http::Method::GET;
                    /// URL path template, with `{name}` placeholders for path
                    /// parameters. Rendering into a concrete URL is the caller's
                    /// responsibility.
                    pub const PATH_TEMPLATE: &'static str = "/v1/models";
                    /// Security requirement declared by the spec for this
                    /// operation. Outer slice encodes OR alternatives; inner
                    /// slice encodes AND requirements within one alternative.
                    /// Empty outer slice means "public, no auth required".
                    pub const SECURITY: &'static [&'static [&'static str]] = &[
                        &["ApiKeyAuth"],
                    ];
                    /// Wraps this request with an `Accept` header override.
                    ///
                    /// The generated [`::toac::MakeRequest`] impl auto-emits an
                    /// `Accept` header listing every response media type
                    /// declared in the spec. Use this method to steer content
                    /// negotiation to one specific type (for example, asking
                    /// for `text/event-stream` to land on a streaming branch).
                    pub fn with_accept(
                        self,
                        accept: ::http::HeaderValue,
                    ) -> ::toac::WithAccept<Self> {
                        ::toac::WithAccept::new(self, accept)
                    }
                }
                impl ::toac::MakeRequest for Request {
                    type Error = ::toac::EncodeRequestError;
                    fn make_request(
                        self,
                    ) -> impl ::std::future::Future<
                        Output = ::std::result::Result<::toac::Request, Self::Error>,
                    > + Send {
                        async move {
                            let mut __path = ::std::string::String::new();
                            __path.push_str("/v1/models");
                            let mut __query_first = true;
                            if let ::std::option::Option::Some(__value) = &self.before_id
                            {
                                ::toac::request::parameter::encode_serialized(
                                        &mut __path,
                                        "before_id",
                                        __value,
                                        ::toac::request::parameter::ParameterStyle::Form,
                                        true,
                                        ::toac::request::parameter::ParameterIn::Query,
                                        &mut __query_first,
                                    )
                                    .map_err(::toac::EncodeRequestError::new)?;
                            }
                            if let ::std::option::Option::Some(__value) = &self.after_id
                            {
                                ::toac::request::parameter::encode_serialized(
                                        &mut __path,
                                        "after_id",
                                        __value,
                                        ::toac::request::parameter::ParameterStyle::Form,
                                        true,
                                        ::toac::request::parameter::ParameterIn::Query,
                                        &mut __query_first,
                                    )
                                    .map_err(::toac::EncodeRequestError::new)?;
                            }
                            if let ::std::option::Option::Some(__value) = &self.limit {
                                ::toac::request::parameter::encode_serialized(
                                        &mut __path,
                                        "limit",
                                        __value,
                                        ::toac::request::parameter::ParameterStyle::Form,
                                        true,
                                        ::toac::request::parameter::ParameterIn::Query,
                                        &mut __query_first,
                                    )
                                    .map_err(::toac::EncodeRequestError::new)?;
                            }
                            let mut __builder = ::http::Request::builder()
                                .method(::http::Method::GET)
                                .uri(__path);
                            __builder = __builder
                                .header(
                                    ::http::header::ACCEPT,
                                    ::http::HeaderValue::from_static("application/json"),
                                );
                            let mut __request = __builder
                                .body(::toac::body::Body::empty())
                                .expect("valid generated HTTP request");
                            __request
                                .extensions_mut()
                                .insert(::toac::OperationSecurity(&[&["ApiKeyAuth"]]));
                            ::std::result::Result::Ok(__request)
                        }
                    }
                }
                #[derive(Debug, Clone, PartialEq)]
                pub enum Response {
                    ///OK
                    Status200(crate::wire::anthropic::components::ListModelsResponse),
                    ///Bad request
                    Status400(crate::wire::anthropic::components::ErrorResponse),
                    ///Authentication failed
                    Status401(crate::wire::anthropic::components::ErrorResponse),
                    ///Rate limited
                    Status429(crate::wire::anthropic::components::ErrorResponse),
                    ///Server error
                    Status500(crate::wire::anthropic::components::ErrorResponse),
                }
                impl ::toac::ParseResponse for Response {
                    type Error = ::toac::DecodeError;
                    fn parse_response<__B>(
                        response: ::http::Response<__B>,
                    ) -> impl ::std::future::Future<
                        Output = ::std::result::Result<Self, Self::Error>,
                    > + ::std::marker::Send
                    where
                        __B: ::http_body::Body<Data = ::bytes::Bytes>
                            + ::std::marker::Send + ::std::marker::Sync + 'static,
                        __B::Error: ::std::convert::Into<::toac::BoxError>,
                    {
                        async move {
                            let (__parts, __body) = response.into_parts();
                            let __status = __parts.status;
                            match __status.as_u16() {
                                200u16 => {
                                    let __decoder = <::toac::body::codec::json::JsonDecoder as ::std::default::Default>::default();
                                    let __value = ::toac::body::codec::decode_body(
                                            &__decoder,
                                            __body,
                                        )
                                        .await
                                        .map_err(|e| ::toac::DecodeError::Codec(
                                            ::std::convert::Into::into(e),
                                        ))?;
                                    return ::std::result::Result::Ok(Self::Status200(__value));
                                }
                                400u16 => {
                                    let __decoder = <::toac::body::codec::json::JsonDecoder as ::std::default::Default>::default();
                                    let __value = ::toac::body::codec::decode_body(
                                            &__decoder,
                                            __body,
                                        )
                                        .await
                                        .map_err(|e| ::toac::DecodeError::Codec(
                                            ::std::convert::Into::into(e),
                                        ))?;
                                    return ::std::result::Result::Ok(Self::Status400(__value));
                                }
                                401u16 => {
                                    let __decoder = <::toac::body::codec::json::JsonDecoder as ::std::default::Default>::default();
                                    let __value = ::toac::body::codec::decode_body(
                                            &__decoder,
                                            __body,
                                        )
                                        .await
                                        .map_err(|e| ::toac::DecodeError::Codec(
                                            ::std::convert::Into::into(e),
                                        ))?;
                                    return ::std::result::Result::Ok(Self::Status401(__value));
                                }
                                429u16 => {
                                    let __decoder = <::toac::body::codec::json::JsonDecoder as ::std::default::Default>::default();
                                    let __value = ::toac::body::codec::decode_body(
                                            &__decoder,
                                            __body,
                                        )
                                        .await
                                        .map_err(|e| ::toac::DecodeError::Codec(
                                            ::std::convert::Into::into(e),
                                        ))?;
                                    return ::std::result::Result::Ok(Self::Status429(__value));
                                }
                                500u16 => {
                                    let __decoder = <::toac::body::codec::json::JsonDecoder as ::std::default::Default>::default();
                                    let __value = ::toac::body::codec::decode_body(
                                            &__decoder,
                                            __body,
                                        )
                                        .await
                                        .map_err(|e| ::toac::DecodeError::Codec(
                                            ::std::convert::Into::into(e),
                                        ))?;
                                    return ::std::result::Result::Ok(Self::Status500(__value));
                                }
                                _ => {}
                            }
                            ::std::mem::drop(__body);
                            return ::std::result::Result::Err(
                                ::toac::DecodeError::UnexpectedStatus(__status),
                            );
                        }
                    }
                }
                impl ::toac::Operation for Request {
                    type Response = Response;
                }
            }
        }
    }
}
pub mod servers {
    #![allow(deprecated)]
    #![allow(unreachable_patterns)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(clippy::all, clippy::pedantic)]
    /// `https://api.anthropic.com`
    /// Anthropic 官方 API endpoint。base_url 由 provider 在 运行期通过 `ANTHROPIC_BASE_URL` env 覆盖（codegen 不参与）。
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
    pub struct ServerOption0;
    impl ::toac::Server for ServerOption0 {
        fn base_url(&self) -> ::std::borrow::Cow<'_, str> {
            ::std::borrow::Cow::Borrowed("https://api.anthropic.com")
        }
    }
    pub type ApiServer = ServerOption0;
}
pub mod security {
    #![allow(deprecated)]
    #![allow(unreachable_patterns)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(clippy::all, clippy::pedantic)]
    /// API-key credential. The value is sent verbatim in the
    /// header / query / cookie slot declared by the spec.
    #[derive(Debug, Clone)]
    pub struct ApiKeyAuthCredential {
        pub value: ::std::string::String,
    }
    impl ApiKeyAuthCredential {
        /// Builds a credential from a raw key value.
        pub fn new<V: ::std::convert::Into<::std::string::String>>(value: V) -> Self {
            Self { value: value.into() }
        }
        /// Projects into the runtime's concrete credential.
        fn as_runtime(&self) -> ::toac::security::ApiKeyCredential {
            ::toac::security::ApiKeyCredential {
                name: "x-api-key",
                location: ::toac::security::ApiKeyLocation::Header,
                value: self.value.clone(),
            }
        }
    }
    impl ::toac::SecurityCredential for ApiKeyAuthCredential {
        fn apply(
            &self,
            req: ::toac::Request,
        ) -> impl ::std::future::Future<
            Output = ::std::result::Result<::toac::Request, ::toac::BoxError>,
        > + ::std::marker::Send {
            let __cred = self.as_runtime();
            async move { ::toac::SecurityCredential::apply(&__cred, req).await }
        }
    }
    /// Aggregate of every credential the spec's security schemes
    /// might need. Each field is optional — callers populate only
    /// the schemes they actually use. Build through
    /// [`AuthConfig::builder`].
    #[derive(Debug, Clone, Default)]
    pub struct AuthConfig {
        pub api_key_auth: ::std::option::Option<ApiKeyAuthCredential>,
    }
    impl AuthConfig {
        /// Starts a fluent builder for [`AuthConfig`]. Each setter
        /// is named after the scheme's key in
        /// `components.securitySchemes`, normalised to snake_case.
        pub fn builder() -> AuthConfigBuilder {
            <AuthConfigBuilder as ::std::default::Default>::default()
        }
    }
    #[derive(Debug, Clone, Default)]
    pub struct AuthConfigBuilder {
        api_key_auth: ::std::option::Option<ApiKeyAuthCredential>,
    }
    impl AuthConfigBuilder {
        /// Provides the API-key credential for this scheme.
        pub fn api_key_auth<V>(mut self, value: V) -> Self
        where
            V: ::std::convert::Into<::std::string::String>,
        {
            self.api_key_auth = ::std::option::Option::Some(
                ApiKeyAuthCredential::new(value),
            );
            self
        }
        /// Finalises into an [`AuthConfig`].
        pub fn build(self) -> AuthConfig {
            let Self { api_key_auth } = self;
            AuthConfig { api_key_auth }
        }
    }
    impl ::toac::AuthSelector for AuthConfig {
        fn apply_for(
            &self,
            req: ::toac::Request,
            requirements: &'static [&'static [&'static str]],
        ) -> ::toac::security::AuthFuture<'_> {
            ::std::boxed::Box::pin(async move {
                if requirements.is_empty() {
                    return ::std::result::Result::Ok(req);
                }
                let mut __chosen: ::std::option::Option<&'static [&'static str]> = ::std::option::Option::None;
                for __alt in requirements {
                    let mut __can_satisfy = true;
                    let mut __matched_any = false;
                    for __scheme in __alt.iter().copied() {
                        if __scheme == "ApiKeyAuth" {
                            let ::std::option::Option::Some(_) = &self.api_key_auth else {
                                __can_satisfy = false;
                                break;
                            };
                            __matched_any = true;
                            continue;
                        }
                        let _ = __matched_any;
                        __can_satisfy = false;
                        break;
                    }
                    if __can_satisfy && __matched_any {
                        __chosen = ::std::option::Option::Some(__alt);
                        break;
                    }
                }
                let ::std::option::Option::Some(__alt) = __chosen else {
                    return ::std::result::Result::Err(
                        ::std::convert::Into::into(
                            ::std::format!(
                                "no configured credentials satisfy {:?}", requirements,
                            ),
                        ),
                    );
                };
                let mut __req = req;
                for __scheme in __alt.iter().copied() {
                    if __scheme == "ApiKeyAuth" {
                        let ::std::option::Option::Some(__cred) = &self.api_key_auth
                        else {
                            continue;
                        };
                        __req = ::toac::SecurityCredential::apply(__cred, __req).await?;
                        continue;
                    }
                }
                ::std::result::Result::Ok(__req)
            })
        }
    }
}
